import io
import json
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.responses import JSONResponse, PlainTextResponse, StreamingResponse
from redis import Redis
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from .db import get_conn, init_db
from .schemas import ReportOut

REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
QUEUE_KEY = os.getenv("QUEUE_KEY", "sos:jobs")
UPLOAD_DIR = Path(os.getenv("UPLOAD_DIR", "/data/uploads"))

app = FastAPI(title="SagaraOps API", version="0.5.0")
redis_client = Redis.from_url(REDIS_URL, decode_responses=True)

ROW_KEYS = ["id", "filename", "status", "severity", "summary", "findings_json", "created_at", "updated_at"]


@app.on_event("startup")
def on_startup() -> None:
    UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
    init_db()


@app.get("/health")
def health():
    return {
        "status": "ok",
        "service": "api",
        "time": datetime.now(timezone.utc).isoformat(),
    }


def _to_report(row) -> ReportOut:
    record = dict(zip(ROW_KEYS, row))
    findings_raw = record.pop("findings_json", None)
    findings = []
    if findings_raw:
        try:
            findings = json.loads(findings_raw)
        except json.JSONDecodeError:
            findings = []
    record["findings"] = findings
    return ReportOut(**record)


def _fetch_report_row(report_id: str):
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, filename, status, severity, summary, findings_json, created_at, updated_at
                FROM reports
                WHERE id = %s;
                """,
                (report_id,),
            )
            return cur.fetchone()


def _build_markdown_report(report: ReportOut) -> str:
    findings_md = "\n".join(
        [
            f"- **[{f.severity.upper()}]** `{f.category}` - `{f.signal}` (count={f.count})\n  - evidence: {f.evidence}"
            for f in report.findings
        ]
    ) or "- No structured findings available."

    summary = report.summary or "No summary generated yet."
    return f"""# Incident Triage Report\n\n## Metadata\n- Report ID: `{report.id}`\n- Filename: `{report.filename}`\n- Status: `{report.status}`\n- Severity: `{report.severity or 'unknown'}`\n- Created At: `{report.created_at.isoformat()}`\n- Updated At: `{report.updated_at.isoformat()}`\n\n## AI Summary\n{summary}\n\n## Structured Findings\n{findings_md}\n\n---\nGenerated by SagaraOps\n"""


def _build_export_package(report: ReportOut) -> dict:
    return {
        "schema_version": "1.0",
        "tool": "SagaraOps",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "report": {
            "id": report.id,
            "filename": report.filename,
            "status": report.status,
            "severity": report.severity,
            "created_at": report.created_at.isoformat(),
            "updated_at": report.updated_at.isoformat(),
        },
        "summary": report.summary,
        "findings": [f.model_dump() for f in report.findings],
    }


def _build_pdf(markdown_text: str) -> bytes:
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    x = 40
    y = height - 40
    line_height = 14

    for raw_line in markdown_text.splitlines():
        line = raw_line.replace("\t", "    ")
        while len(line) > 110:
            pdf.drawString(x, y, line[:110])
            y -= line_height
            line = line[110:]
            if y < 40:
                pdf.showPage()
                y = height - 40
        pdf.drawString(x, y, line)
        y -= line_height
        if y < 40:
            pdf.showPage()
            y = height - 40

    pdf.save()
    buffer.seek(0)
    return buffer.read()


@app.post("/v1/reports/upload", response_model=ReportOut)
async def upload_report(file: UploadFile = File(...)):
    report_id = str(uuid.uuid4())
    safe_name = file.filename or f"report-{report_id}.tar.xz"
    target_path = UPLOAD_DIR / f"{report_id}-{safe_name}"

    content = await file.read()
    target_path.write_bytes(content)

    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO reports (id, filename, filepath, status, severity, summary, findings_json)
                VALUES (%s, %s, %s, %s, %s, %s, %s)
                RETURNING id, filename, status, severity, summary, findings_json, created_at, updated_at;
                """,
                (report_id, safe_name, str(target_path), "queued", None, None, None),
            )
            row = cur.fetchone()
        conn.commit()

    redis_client.lpush(
        QUEUE_KEY,
        json.dumps(
            {
                "report_id": report_id,
                "filepath": str(target_path),
            }
        ),
    )

    return _to_report(row)


@app.get("/v1/reports", response_model=list[ReportOut])
def list_reports(limit: int = 20):
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, filename, status, severity, summary, findings_json, created_at, updated_at
                FROM reports
                ORDER BY created_at DESC
                LIMIT %s;
                """,
                (max(1, min(limit, 100)),),
            )
            rows = cur.fetchall()

    return [_to_report(row) for row in rows]


@app.get("/v1/reports/{report_id}", response_model=ReportOut)
def get_report(report_id: str):
    row = _fetch_report_row(report_id)
    if not row:
        raise HTTPException(status_code=404, detail="Report not found")
    return _to_report(row)


@app.get("/v1/reports/{report_id}/export.md", response_class=PlainTextResponse)
def export_report_markdown(report_id: str):
    row = _fetch_report_row(report_id)
    if not row:
        raise HTTPException(status_code=404, detail="Report not found")

    report = _to_report(row)
    return _build_markdown_report(report)


@app.get("/v1/reports/{report_id}/export.json")
def export_report_json(report_id: str):
    row = _fetch_report_row(report_id)
    if not row:
        raise HTTPException(status_code=404, detail="Report not found")

    report = _to_report(row)
    pkg = _build_export_package(report)
    return JSONResponse(pkg)


@app.get("/v1/reports/{report_id}/export.pdf")
def export_report_pdf(report_id: str):
    row = _fetch_report_row(report_id)
    if not row:
        raise HTTPException(status_code=404, detail="Report not found")

    report = _to_report(row)
    markdown = _build_markdown_report(report)
    pdf_data = _build_pdf(markdown)

    return StreamingResponse(
        io.BytesIO(pdf_data),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=triage-{report_id}.pdf"},
    )
